app = 'sniproxy'
primary_region = 'nrt'

[build]
dockerfile = 'Dockerfile'

[[vm]]
memory = '1gb'
memory_mb = 256
cpu_kind = 'shared'
cpus = 1

[[services]]
internal_port = 80
protocol = 'tcp'
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1

[[services.ports]]
port = 80
handlers = ['http']

[[services.ports]]
port = 443
handlers = ['tls', 'http']

[[services.checks]]
type = 'http'
path = '/'
interval = '10s'
timeout = '2s'
grace_period = '5s'